export const TASK_LIST_REQUEST = "TASK_LIST_REQUEST";
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS";
export const TASK_LIST_FAIL = "TASK_LIST_FAIL";

export const TASK_LIST_USER_REQUEST = "TASK_LIST_USER_REQUEST";
export const TASK_LIST_USER_SUCCESS = "TASK_LIST_USER_SUCCESS";
export const TASK_LIST_USER_FAIL = "TASK_LIST_USER_FAIL";

export const TASK_DETAILS_REQUEST = "TASK_DETAILS_REQUEST";
export const TASK_DETAILS_SUCCESS = "TASK_DETAILS_SUCCESS";
export const TASK_DETAILS_FAIL = "TASK_DETAILS_FAIL";

export const TASK_SAVE_REQUEST = "TASK_SAVE_REQUEST";
export const TASK_SAVE_SUCCESS = "TASK_SAVE_SUCCESS";
export const TASK_SAVE_FAIL = "TASK_SAVE_FAIL";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";

export const TASK_CLONE_REQUEST = "TASK_CLONE_REQUEST";
export const TASK_CLONE_SUCCESS = "TASK_CLONE_SUCCESS";
export const TASK_CLONE_FAIL = "TASK_CLONE_FAIL";
